// dashboard/src/app/app.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subject, takeUntil } from 'rxjs';
import { ExceptionStreamService } from './services/exception-stream.service';
import { ApiService } from './services/api.service';
import { AgentPipelineComponent } from './components/agent-pipeline/agent-pipeline.component';
import { WorkflowVisualizerComponent } from './components/workflow-visualizer/workflow-visualizer.component';
import { LiveEventStreamComponent } from './components/live-event-stream/live-event-stream.component';
import { ResolutionMetricsComponent } from './components/resolution-metrics/resolution-metrics.component';
import { CostTrackerComponent } from './components/cost-tracker/cost-tracker.component';
import { Exception, TotalStats } from './models/exception.model';

const SCENARIO_ICONS: Record<string, string> = {
  delay:          '🌩️',
  lost:           '🔍',
  damaged:        '📦',
  address_issue:  '📍',
  customs_hold:   '🛃',
  failed_delivery:'🚚',
};

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    AgentPipelineComponent,
    WorkflowVisualizerComponent,
    LiveEventStreamComponent,
    ResolutionMetricsComponent,
    CostTrackerComponent,
  ],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit, OnDestroy {
  exceptions: Exception[] = [];
  wsStatus = 'connecting';
  stats: TotalStats = this.emptyStats();
  activeCount = 0;

  simulating    = false;
  lastScenario: string | null = null;
  simError:     string | null = null;

  scenarios = Object.entries(SCENARIO_ICONS).map(([key, icon]) => ({
    key, icon, label: key.replace(/_/g, ' '),
  }));

  private destroy$ = new Subject<void>();

  constructor(
    private stream: ExceptionStreamService,
    private api:    ApiService,
  ) {}

  ngOnInit(): void {
    this.stream.exceptions$.pipe(takeUntil(this.destroy$)).subscribe(excs => {
      this.exceptions   = excs;
      this.stats        = this.stream.computeStats(excs);
      this.activeCount  = excs.filter(e => !['resolved', 'failed'].includes(e.workflow_status)).length;
    });
    this.stream.wsStatus$.pipe(takeUntil(this.destroy$)).subscribe(s => {
      this.wsStatus = s;
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  wsStatusClass(): string {
    const map: Record<string, string> = {
      connected:    'bg-green-400',
      connecting:   'bg-yellow-400 animate-pulse',
      disconnected: 'bg-red-400',
      error:        'bg-red-400',
    };
    return map[this.wsStatus] ?? 'bg-gray-300';
  }

  handleSimulate(scenario: string | null): void {
    if (this.simulating || this.wsStatus !== 'connected') return;
    this.simulating   = true;
    this.simError     = null;
    this.lastScenario = scenario;
    this.api.triggerSimulation(scenario).subscribe({
      next:  () => { this.simulating = false; },
      error: (err: any) => { this.simError = err.message ?? 'Unknown error'; this.simulating = false; },
    });
  }

  onScenarioChange(event: Event): void {
    const val = (event.target as HTMLSelectElement).value;
    if (val) {
      this.handleSimulate(val);
      (event.target as HTMLSelectElement).value = '';
    }
  }

  scenarioIcon(key: string): string {
    return SCENARIO_ICONS[key] ?? '';
  }

  private emptyStats(): TotalStats {
    return {
      resolved: 0, failed: 0, active: 0,
      bySeverity: {}, byType: {}, byResolution: {},
      totalCost: 0, totalInput: 0, totalOutput: 0,
      agentStats: [],
    };
  }
}

<div class="min-h-screen bg-gray-50 text-gray-800">

  <!-- Header -->
  <header class="bg-white border-b border-gray-200 px-5 py-2.5 flex items-center justify-between sticky top-0 z-10 gap-4">

    <!-- Left: logo + WS status -->
    <div class="flex items-center gap-2.5 shrink-0">
      <div class="w-2 h-2 rounded-full" [ngClass]="wsStatusClass()"></div>
      <h1 class="text-sm font-bold text-gray-800 tracking-tight">Logistics Exception Dashboard</h1>
      <span class="text-xs text-gray-400 hidden sm:inline">
        <ng-container [ngSwitch]="wsStatus">
          <ng-container *ngSwitchCase="'connected'">● live</ng-container>
          <ng-container *ngSwitchCase="'connecting'">⟳ connecting…</ng-container>
          <ng-container *ngSwitchCase="'disconnected'">○ reconnecting…</ng-container>
        </ng-container>
      </span>
    </div>

    <!-- Middle: simulate controls -->
    <div class="flex items-center gap-2 flex-wrap justify-center">
      <button
        (click)="handleSimulate(null)"
        [disabled]="simulating || wsStatus !== 'connected'"
        class="text-xs px-3 py-1.5 rounded-md font-medium transition-colors flex items-center gap-1.5"
        [ngClass]="simulating || wsStatus !== 'connected'
          ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
          : 'bg-indigo-600 text-white hover:bg-indigo-700'"
      >
        {{ simulating ? '⟳ Running…' : '⚡ Simulate Exception' }}
      </button>

      <select
        class="text-xs border border-gray-200 rounded-md px-2 py-1.5 text-gray-600 bg-white hover:border-gray-300 focus:outline-none disabled:opacity-50"
        [disabled]="simulating || wsStatus !== 'connected'"
        (change)="onScenarioChange($event)"
      >
        <option value="" disabled selected>Pick scenario…</option>
        <option *ngFor="let s of scenarios" [value]="s.key">{{ s.icon }} {{ s.label }}</option>
      </select>

      <span *ngIf="lastScenario && !simulating" class="text-xs text-gray-400">
        last: {{ scenarioIcon(lastScenario) }} {{ lastScenario }}
      </span>
      <span *ngIf="simError" class="text-xs text-red-500 max-w-xs truncate" [title]="simError">
        ⚠ {{ simError }}
      </span>
    </div>

    <!-- Right: counters -->
    <div class="flex items-center gap-3 shrink-0">
      <span *ngIf="activeCount > 0" class="text-xs text-blue-500 font-medium">
        {{ activeCount }} active
      </span>
      <span class="text-xs text-gray-400">{{ exceptions.length }} total</span>
    </div>
  </header>

  <main class="p-4 space-y-4 max-w-screen-xl mx-auto">

    <!-- Agent summary row -->
    <div class="bg-white rounded-xl border border-gray-200 p-4">
      <app-agent-pipeline [exceptions]="exceptions" [agentStats]="stats.agentStats"></app-agent-pipeline>
    </div>

    <!-- Workflow detail + live stream -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="lg:col-span-2 bg-white rounded-xl border border-gray-200 p-4 overflow-y-auto" style="max-height:640px">
        <app-workflow-visualizer [exceptions]="exceptions"></app-workflow-visualizer>
      </div>
      <div class="bg-white rounded-xl border border-gray-200 p-4 flex flex-col" style="max-height:640px">
        <app-live-event-stream [exceptions]="exceptions"></app-live-event-stream>
      </div>
    </div>

    <!-- Metrics row -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="bg-white rounded-xl border border-gray-200 p-4">
        <app-resolution-metrics [stats]="stats"></app-resolution-metrics>
      </div>
      <div class="bg-white rounded-xl border border-gray-200 p-4">
        <app-cost-tracker [stats]="stats"></app-cost-tracker>
      </div>
    </div>

  </main>
</div>

// dashboard/src/App.jsx
import { useState } from 'react'
import AgentPipeline from './components/AgentPipeline'
import CostTracker from './components/CostTracker'
import LiveEventStream from './components/LiveEventStream'
import ResolutionMetrics from './components/ResolutionMetrics'
import WorkflowVisualizer from './components/WorkflowVisualizer'
import { useExceptionStream } from './hooks/useExceptionStream'
import { fetchScenarios, triggerSimulation } from './lib/api'
import { totalStats } from './lib/mockGenerator'

const WS_STATUS_STYLES = {
  connected:    'bg-green-400',
  connecting:   'bg-yellow-400 animate-pulse',
  disconnected: 'bg-red-400',
  error:        'bg-red-400',
}

const SCENARIO_ICONS = {
  delay:          '🌩️',
  lost:           '🔍',
  damaged:        '📦',
  address_issue:  '📍',
  customs_hold:   '🛃',
  failed_delivery:'🚚',
}

export default function App() {
  const { exceptions, wsStatus } = useExceptionStream()
  const [simulating,  setSimulating]  = useState(false)
  const [lastScenario, setLastScenario] = useState(null)
  const [simError,    setSimError]    = useState(null)

  // Aggregate stats — same computation works for both real + mock shapes
  const byResolution = {}
  for (const e of exceptions) {
    if (e.resolution_type) {
      byResolution[e.resolution_type] = (byResolution[e.resolution_type] || 0) + 1
    }
  }
  const stats = { ...totalStats(exceptions), byResolution }

  const activeCount = exceptions.filter(
    e => !['resolved', 'failed'].includes(e.workflow_status)
  ).length

  async function handleSimulate(scenario) {
    setSimulating(true)
    setSimError(null)
    setLastScenario(scenario ?? null)
    try {
      await triggerSimulation(scenario ?? null)
    } catch (err) {
      setSimError(err.message)
    } finally {
      setSimulating(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 text-gray-800">
      {/* ── Header ───────────────────────────────────────────────────────────── */}
      <header className="bg-white border-b border-gray-200 px-5 py-2.5 flex items-center justify-between sticky top-0 z-10 gap-4">
        {/* Left: logo + WS status */}
        <div className="flex items-center gap-2.5 shrink-0">
          <div className={`w-2 h-2 rounded-full ${WS_STATUS_STYLES[wsStatus] ?? 'bg-gray-300'}`} />
          <h1 className="text-sm font-bold text-gray-800 tracking-tight">
            Logistics Exception Dashboard
          </h1>
          <span className="text-xs text-gray-400 hidden sm:inline">
            {wsStatus === 'connected'    && '● live'}
            {wsStatus === 'connecting'   && '⟳ connecting…'}
            {wsStatus === 'disconnected' && '○ reconnecting…'}
          </span>
        </div>

        {/* Middle: simulate controls */}
        <div className="flex items-center gap-2 flex-wrap justify-center">
          {/* Quick-fire random scenario */}
          <button
            onClick={() => handleSimulate(null)}
            disabled={simulating || wsStatus !== 'connected'}
            className={`
              text-xs px-3 py-1.5 rounded-md font-medium transition-colors
              flex items-center gap-1.5
              ${simulating || wsStatus !== 'connected'
                ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                : 'bg-indigo-600 text-white hover:bg-indigo-700'}
            `}
          >
            {simulating ? '⟳ Running…' : '⚡ Simulate Exception'}
          </button>

          {/* Scenario picker */}
          <select
            className="text-xs border border-gray-200 rounded-md px-2 py-1.5 text-gray-600 bg-white hover:border-gray-300 focus:outline-none disabled:opacity-50"
            defaultValue=""
            disabled={simulating || wsStatus !== 'connected'}
            onChange={e => { if (e.target.value) handleSimulate(e.target.value); e.target.value = '' }}
          >
            <option value="" disabled>Pick scenario…</option>
            {Object.entries(SCENARIO_ICONS).map(([key, icon]) => (
              <option key={key} value={key}>{icon} {key.replace('_', ' ')}</option>
            ))}
          </select>

          {/* Last triggered indicator */}
          {lastScenario && !simulating && (
            <span className="text-xs text-gray-400">
              last: {SCENARIO_ICONS[lastScenario]} {lastScenario}
            </span>
          )}
          {simError && (
            <span className="text-xs text-red-500 max-w-xs truncate" title={simError}>
              ⚠ {simError}
            </span>
          )}
        </div>

        {/* Right: counters */}
        <div className="flex items-center gap-3 shrink-0">
          {activeCount > 0 && (
            <span className="text-xs text-blue-500 font-medium">
              {activeCount} active
            </span>
          )}
          <span className="text-xs text-gray-400">{exceptions.length} total</span>
        </div>
      </header>

      <main className="p-4 space-y-4 max-w-screen-xl mx-auto">
        {/* ── Agent summary row ───────────────────────────────────────────────── */}
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <AgentPipeline exceptions={exceptions} agentStats={stats.agentStats} />
        </div>

        {/* ── Workflow detail + live stream ────────────────────────────────────── */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div
            className="lg:col-span-2 bg-white rounded-xl border border-gray-200 p-4 overflow-y-auto"
            style={{ maxHeight: 640 }}
          >
            <WorkflowVisualizer exceptions={exceptions} />
          </div>
          <div
            className="bg-white rounded-xl border border-gray-200 p-4 flex flex-col"
            style={{ maxHeight: 640 }}
          >
            <LiveEventStream exceptions={exceptions} />
          </div>
        </div>

        {/* ── Metrics row ─────────────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white rounded-xl border border-gray-200 p-4">
            <ResolutionMetrics stats={stats} />
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-4">
            <CostTracker stats={stats} />
          </div>
        </div>
      </main>
    </div>
  )
}
