// dashboard/src/app/components/cost-tracker/cost-tracker.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AGENTS, AgentDef, TotalStats } from '../../models/exception.model';

const CIN  = 0.000003;
const COUT = 0.000015;

const AGENT_BAR_COLORS: Record<string, string> = {
  blue: 'bg-blue-400', violet: 'bg-violet-400', amber: 'bg-amber-400',
  emerald: 'bg-emerald-400', rose: 'bg-rose-400',
};

@Component({
  selector: 'app-cost-tracker',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './cost-tracker.component.html',
})
export class CostTrackerComponent {
  @Input() stats!: TotalStats;

  agents: AgentDef[] = AGENTS;

  get totalCost():   number { return this.stats?.totalCost   ?? 0; }
  get totalInput():  number { return this.stats?.totalInput  ?? 0; }
  get totalOutput(): number { return this.stats?.totalOutput ?? 0; }
  get resolved():    number { return this.stats?.resolved    ?? 0; }

  get apiCalls():      number { return (this.stats?.agentStats ?? []).reduce((s, a) => s + a.runs, 0); }
  get avgCostPerEx():  number { return this.resolved > 0 ? this.totalCost / this.resolved : 0; }
  get maxAgentCost():  number { return Math.max(...(this.stats?.agentStats ?? []).map(a => a.costUsd), 0.000001); }
  get hasTokens():     boolean { return (this.totalInput + this.totalOutput) > 0; }

  inputPct():  number { return this.hasTokens ? (this.totalInput  / (this.totalInput + this.totalOutput)) * 100 : 50; }
  outputPct(): number { return this.hasTokens ? (this.totalOutput / (this.totalInput + this.totalOutput)) * 100 : 50; }

  agentCost(key: string): number { return this.stats?.agentStats.find(s => s.key === key)?.costUsd ?? 0; }
  agentBarPct(key: string): number { return this.maxAgentCost > 0 ? (this.agentCost(key) / this.maxAgentCost) * 100 : 0; }
  agentBarColor(color: string): string { return AGENT_BAR_COLORS[color] ?? 'bg-gray-400'; }

  inputCostDisplay():  string { return (this.totalInput  * CIN ).toFixed(4); }
  outputCostDisplay(): string { return (this.totalOutput * COUT).toFixed(4); }
  inputPctLabel():     string { return Math.round(this.inputPct())  + '% input'; }
  outputPctLabel():    string { return Math.round(this.outputPct()) + '% output'; }
}

<div class="space-y-5">
  <h2 class="text-sm font-semibold text-gray-700 uppercase tracking-wider">Cost Tracking</h2>

  <!-- Top stats -->
  <div class="grid grid-cols-2 gap-2">
    <div class="p-3 rounded-lg bg-gray-50">
      <div class="text-xs text-gray-500 mb-0.5">Total API cost</div>
      <div class="text-lg font-bold text-gray-800">${{ totalCost.toFixed(4) }}</div>
      <div class="text-xs text-gray-400 mt-0.5">{{ apiCalls }} API calls</div>
    </div>
    <div class="p-3 rounded-lg bg-gray-50">
      <div class="text-xs text-gray-500 mb-0.5">Avg cost / exception</div>
      <div class="text-lg font-bold text-gray-800">${{ avgCostPerEx.toFixed(4) }}</div>
      <div class="text-xs text-gray-400 mt-0.5">{{ resolved }} resolved</div>
    </div>
    <div class="p-3 rounded-lg bg-gray-50">
      <div class="text-xs text-gray-500 mb-0.5">Input tokens</div>
      <div class="text-lg font-bold text-gray-800">{{ totalInput.toLocaleString() }}</div>
      <div class="text-xs text-gray-400 mt-0.5">${{ inputCostDisplay() }}</div>
    </div>
    <div class="p-3 rounded-lg bg-gray-50">
      <div class="text-xs text-gray-500 mb-0.5">Output tokens</div>
      <div class="text-lg font-bold text-gray-800">{{ totalOutput.toLocaleString() }}</div>
      <div class="text-xs text-gray-400 mt-0.5">${{ outputCostDisplay() }}</div>
    </div>
  </div>

  <!-- Per-agent cost breakdown -->
  <div>
    <p class="text-xs text-gray-400 mb-2 uppercase tracking-wider">Cost by agent</p>
    <div class="space-y-2">
      <div *ngFor="let agent of agents" class="space-y-0.5">
        <div class="flex justify-between text-xs">
          <span class="text-gray-500">{{ agent.label }}</span>
          <span class="font-medium text-gray-700">${{ agentCost(agent.key).toFixed(4) }}</span>
        </div>
        <div class="h-1.5 bg-gray-100 rounded-full overflow-hidden">
          <div [ngClass]="'h-full rounded-full ' + agentBarColor(agent.color)"
               [style.width.%]="agentBarPct(agent.key)"
               style="transition: width 0.4s ease">
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Token ratio -->
  <div *ngIf="hasTokens">
    <p class="text-xs text-gray-400 mb-1.5 uppercase tracking-wider">Token ratio (input / output)</p>
    <div class="flex h-2 rounded-full overflow-hidden">
      <div class="bg-blue-300 transition-all" [style.width.%]="inputPct()"></div>
      <div class="flex-1 bg-violet-300"></div>
    </div>
    <div class="flex justify-between text-xs text-gray-400 mt-1">
      <span>{{ inputPctLabel() }}</span>
      <span>{{ outputPctLabel() }}</span>
    </div>
  </div>
</div>

// dashboard/src/components/CostTracker.jsx
import { AGENTS } from '../lib/mockGenerator'

const CIN  = 0.000003
const COUT = 0.000015

function Stat({ label, value, sub }) {
  return (
    <div className="p-3 rounded-lg bg-gray-50">
      <div className="text-xs text-gray-500 mb-0.5">{label}</div>
      <div className="text-lg font-bold text-gray-800">{value}</div>
      {sub && <div className="text-xs text-gray-400 mt-0.5">{sub}</div>}
    </div>
  )
}

const AGENT_BAR_COLORS = {
  blue:    'bg-blue-400',
  violet:  'bg-violet-400',
  amber:   'bg-amber-400',
  emerald: 'bg-emerald-400',
  rose:    'bg-rose-400',
}

export default function CostTracker({ stats }) {
  const {
    totalCost = 0,
    totalInput = 0,
    totalOutput = 0,
    agentStats = [],
    resolved = 0,
  } = stats || {}

  const apiCalls     = agentStats.reduce((s, a) => s + a.runs, 0)
  const avgCostPerEx = resolved > 0 ? totalCost / resolved : 0
  const maxAgentCost = Math.max(...agentStats.map(a => a.costUsd), 0.000001)

  return (
    <div className="space-y-5">
      <h2 className="text-sm font-semibold text-gray-700 uppercase tracking-wider">
        Cost Tracking
      </h2>

      {/* Top stats */}
      <div className="grid grid-cols-2 gap-2">
        <Stat
          label="Total API cost"
          value={`$${totalCost.toFixed(4)}`}
          sub={`${apiCalls} API calls`}
        />
        <Stat
          label="Avg cost / exception"
          value={`$${avgCostPerEx.toFixed(4)}`}
          sub={`${resolved} resolved`}
        />
        <Stat
          label="Input tokens"
          value={totalInput.toLocaleString()}
          sub={`$${(totalInput * CIN).toFixed(4)}`}
        />
        <Stat
          label="Output tokens"
          value={totalOutput.toLocaleString()}
          sub={`$${(totalOutput * COUT).toFixed(4)}`}
        />
      </div>

      {/* Per-agent cost breakdown */}
      <div>
        <p className="text-xs text-gray-400 mb-2 uppercase tracking-wider">
          Cost by agent
        </p>
        <div className="space-y-2">
          {AGENTS.map(agent => {
            const s   = agentStats.find(x => x.key === agent.key)
            const cost = s?.costUsd ?? 0
            const pct  = maxAgentCost > 0 ? (cost / maxAgentCost) * 100 : 0
            const bar  = AGENT_BAR_COLORS[agent.color]

            return (
              <div key={agent.key} className="space-y-0.5">
                <div className="flex justify-between text-xs">
                  <span className="text-gray-500">{agent.label}</span>
                  <span className="font-medium text-gray-700">${cost.toFixed(4)}</span>
                </div>
                <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full ${bar}`}
                    style={{ width: `${pct}%`, transition: 'width 0.4s ease' }}
                  />
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Token ratio */}
      {(totalInput + totalOutput) > 0 && (
        <div>
          <p className="text-xs text-gray-400 mb-1.5 uppercase tracking-wider">
            Token ratio (input / output)
          </p>
          <div className="flex h-2 rounded-full overflow-hidden">
            <div
              className="bg-blue-300 transition-all"
              style={{ width: `${(totalInput / (totalInput + totalOutput)) * 100}%` }}
            />
            <div className="flex-1 bg-violet-300" />
          </div>
          <div className="flex justify-between text-xs text-gray-400 mt-1">
            <span>{Math.round((totalInput / (totalInput + totalOutput)) * 100)}% input</span>
            <span>{Math.round((totalOutput / (totalInput + totalOutput)) * 100)}% output</span>
          </div>
        </div>
      )}
    </div>
  )
}
